#!/bin/bash
# Ensure our custom Procfile is used and not auto-generated by EB

# This hook runs before EB processes the Procfile
# We'll create a marker file to indicate we have a custom Procfile
echo "Using custom Procfile with Uvicorn workers" > /tmp/custom_procfile_marker
